# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Immortal < Formula
  desc "Self-healing engine. Your apps never die."
  homepage "https://github.com/Nagendhra-web/Immortal"
  version "0.6.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nagendhra-web/Immortal/releases/download/v0.6.3/immortal_darwin_amd64.tar.gz"
      sha256 "fb59ba2d6a36aa5093044c8ff222422f9bc7e00d5d8a2ff624f2603cc2edb0b2"

      define_method(:install) do
        bin.install "immortal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nagendhra-web/Immortal/releases/download/v0.6.3/immortal_darwin_arm64.tar.gz"
      sha256 "4aa38cff4656be25c46856daea2201072d9c30b301f82c94b6880fbf886cf89c"

      define_method(:install) do
        bin.install "immortal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nagendhra-web/Immortal/releases/download/v0.6.3/immortal_linux_amd64.tar.gz"
      sha256 "c263f3bf3dbaf8669f49127d37a5126cb01ca27ea27db8e007661c58dd9762a2"
      define_method(:install) do
        bin.install "immortal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nagendhra-web/Immortal/releases/download/v0.6.3/immortal_linux_arm64.tar.gz"
      sha256 "6867d3e59f40a65f9775aa3d09eded220eac084f80166503197d3157998a1196"
      define_method(:install) do
        bin.install "immortal"
      end
    end
  end

  test do
    system "#{bin}/immortal", "version"
  end
end
